### PR TITLE
Added DomainIntentEngine

### PR DESCRIPTION
**Pull request by the-kid89**
My git branch was rather messed up so I just started a new one.

This is all the code from "https://github.com/MycroftAI/adapt/pull/24" just in a format that can be merged without issues.

### CODE REVIEW

**Comment by ryanleesipes** [comment]
@clusterfudge can you take a look at this?

**Comment by the-kid89** [comment]
I would really like to get this merged in so I can use it in a project I'm working on.

**Comment by clusterfudge** [comment]
yup, let's do it.

**Comment by clusterfudge** [comment]
released with v0.2.2

**Pull request merged**
