### PR TITLE
Context

### PR DESCRIPTION
**Pull request by clusterfudge**
will rebase off origin, please review.

### CODE REVIEW

**Comment by penrods** [comment]
Very interesting.  I've been thinking about context and how to merge some of what I built into Mycroft.  Let me make sure my thinking here is right:  this would allow Mycroft to have a lexicon of known entities (like "Location") that Mycroft could pre-populate -- e.g. default location would be based on the account info -- and maintain -- e.g. after 5 minutes the default "Location" would revert to the default location instead of a one-off question you asked about the weather elsewhere.  Essentially there would be a MycroftContextManager() to handle this, right?

**Comment by clusterfudge** [comment]
So, the lexicon is managed by an instance of ContextManager (in this current implementation). I intended to let higher level systems like Mycroft manage the concept of a session (be it time based, device based, combination of the two, etc) with instances of ContextManager. These instances could be managed either by the IntentSkill or a separate ContextSkill.

It would be possible for Mycroft to manage population of user defaults, or info from sensors (location, status of IoT devices, etc) in various skills. I had not originally intended ContextManager to be used for user profile info; I can't put words to it right now, but I think there's a more elegant solution. There's nothing preventing that.

**Comment by penrods** [comment]
I didn't really intend it to be user profile info, sorry if that was implied.  But I *do* imagine 'user' would be one of the entities.  It isn't happening today, but ultimately I want the wake word to identify if it was spoken by a 'registered user' via a voiceprint.  Then part of the session's context would be something like 'User', so you could handle 'What is on Bob's calendar today' or 'What is on the calendar today', where the former would extract 'User' = 'Bob' and the former would get 'User' from the ContextManager, which would look at who woke up the device.  (In reality it'll be UserIDs, but I think you get the idea.)

Things like 'Location' would depend on the Enclosure implementation.  Many would be static (like the original Mycroft device) and would just get the location of the device from the device settings.  But a CarEnclosure or iPhoneEnclosure would get 'Location' from the GPS.

Anyway, this looks very interesting.  I think we can do some good stuff with it!

**Comment by clusterfudge** [comment]
I have a couple more tests to write, but wanted to get the ball rolling on a review. If you don't have any more feedback on it, I'll update tonight and we can talk about a merge strategy soon.

Just to be explicit, the 0.3.0 update is backwards compatible, both in api and functionality.

**Comment by penrods** [comment]
It looked like it was going to be painless, I didn't see anything that looked like breaking API changes.  I'm good with the direction you are heading!

**Comment by clusterfudge** [comment]
@penrods if you don't have any more comments, I think this is ready to go.

**Comment by clusterfudge** [comment]
@penrods were there any questions on this?

**Comment by penrods** [comment]
Things look good at first blush.  I want to give it a thorough look-over (for myself as much as for you) before I merge this request.  Probably either today or tomorrow.

**Comment by clusterfudge** [comment]
@penrods Anything I can do to move this along?

**Comment by penrods** [comment]
LGTM

**Pull request merged**
