### PR TITLE
Update engine.py (fix typos in docstring)

### PR DESCRIPTION
**Pull request by PLNech**
* Description of what the PR does, such as fixes # {issue number}
Fixes typos in some Engine's docstrings

* Description of how to validate or test this PR
Nothing (Pure documentation change)

* Whether you have signed a CLA (Contributor Licensing Agreement)
Sent!

### CODE REVIEW

**Comment by forslund** [comment]
Hi, @PLNech thank you for these comment fixes. We welcome everyone into the community and greatly appreciate your help as we work to build an AI for Everyone.
  
To protect yourself, the project, and users of Mycroft technologies we require a Contributor Licensing Agreement (CLA) before accepting any code contribution. This agreement makes it crystal clear that along with your code you are offering a license to use it within the confines of this project. You retain ownership of the code, this is just a license.
 
Please visit https://mycroft.ai/cla to initiate this one-time signing. Thank you!

**Comment by forslund** [comment]
Sorry for the CLA thing just read your comment down to the last bullet point where you say it's sent. When it arrives we can merge this. Once more, thank you.

**Comment by PLNech** [comment]
Hey, sorry for the slow reply, CLA signed!

**Comment by krisgesling** [comment]
CLA received, thanks Paul-Louis :)

@forslund I don't have write permissions on this repo so you'll have to merge this one

**Comment by forslund** [comment]
Sorry for the delay, totally missed the ping from @krisgesling.

Many thanks for this @PLNech, Merging now!

**Pull request merged**
