### PR TITLE
Set formating of example to right language

### PR DESCRIPTION
**Pull request by nallath**
* Description of what the PR does, such as fixes # {issue number}
This prettifies the formatting of the example snippets.

* Description of how to validate or test this PR
Nothing to test. 

* Whether you have signed a CLA (Contributor Licensing Agreement)
Nope, but change is so minor that i doubt it even matters (Formatting changes aren't even something you can hold copyrights on)

### CODE REVIEW

**Comment by penrods** [comment]
Hello, @nallath, thank you for helping with the Mycroft project! We welcome
everyone into the community and greatly appreciate your help as we work to
build an AI for Everyone.
  
To protect yourself, the project, and users of Mycroft technologies we require
a Contributor Licensing Agreement (CLA) before accepting any code contribution.
This agreement makes it crystal clear that along with your code you are
offering a license to use it within the confines of this project. You retain
ownership of the code, this is just a license.
 
Please visit https://mycroft.ai/cla to initiate this one-time signing. Thank you!

**Comment by nallath** [comment]
I've requested the CLA. Let's wait until it's there.

**Comment by forslund** [comment]
Hi @nallath did you get the CLA e-mail ok? I don't see you on our list of signed CLA's?

**Comment by forslund** [comment]
If you don't get an e-mail within the day check your spam folder

**Comment by penrods** [comment]
I saw a CLA request from you this morning, you should have a HelloSign email in your mailbox.  I didn't see one before that -- not sure what happened.  Sorry!

**Comment by nallath** [comment]
No problem! I've signed it, so all should be good now.

**Comment by forslund** [comment]
CLA has arrived. Merging. Thank you very much.

**Pull request merged**
