### PR TITLE
error in TrieNode.is_prefix #53

### PR DESCRIPTION
**Pull request by SoloVeniaASaludar**
See issue #53 for details

### CODE REVIEW

**Comment by clusterfudge** [comment]
Adapt doesn't actually use this method (and it has no unit test coverage), so it would be just as simple to remove it altogether. How did you come across this problem?

**Comment by SoloVeniaASaludar** [comment]
Thanks for your answer.

I've come to this code learning how mycroft is done.

OK about delete or correct it.

Also lookup method has several issues. By example, when executed with a single intent "abcd" and lookup utterance "abxyd" (with max_distance=10, by example), the result is an edit_distance equal to one , instead the expected two (substitution c<->x and insert d).

I can provide a pull request with a possible fix, if interested in.

**Comment by clusterfudge** [comment]
Sorry for the delayed response on this.

I'm fine seeing the fix for the crash here. I'd also like to see a unit test that verifies the fix.

I'm also fine seeing a PR that fixes edit distance calculations, with it's associated unit tests.

**Comment by clusterfudge** [comment]
closing in favor of #148

**Pull request closed without merging**
