### PR TITLE
Bump version to 1.0.0 and mark stable.

### PR DESCRIPTION
**Pull request by clusterfudge**
* Description of what the PR does, such as fixes # {issue number}
Bump version to 1.0.0 and mark as stable.

* Description of how to validate or test this PR
No logical changes.

* Whether you have signed a CLA (Contributor Licensing Agreement)
yes

### CODE REVIEW

**Comment by forslund** [comment]
Hooray! Great work!

**Review by krisgesling — APPROVED** [review]
:tada: Woooh! :tada:

A huge milestone and massive effort to get it there - thanks so much!

**Comment by krisgesling** [comment]
Ah looks like the PyPI classifier should be:

```
Development Status :: 5 - Production/Stable
```

**Comment by PureTryOut** [comment]
Maybe make it a proper release on Github rather than a boring git tag only? :stuck_out_tongue_winking_eye:

**Pull request merged**
